[package]
name = "rust-prob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fn-memo = "1.2.0"
memoize = "0.2.1"
num = "0.4.0"
probability = "0.18.0"
